### ISSUE TITLE
Travis CI failing -- But run-tests.sh succeeds locally

### ISSUE THREAD

**Issue by Rangak** [EFForg/OpenWireless#269]
We have Travis CI set up here: https://travis-ci.org/EFForg/OpenWireless

The builds are failing in Travis but not locally, for example: https://travis-ci.org/EFForg/OpenWireless/builds/47143106

Failed with:

``` bash
======================================================================

FAIL: test_change_password_first_time (change_password_first_time_test.TestChangePasswordFirstTime)

----------------------------------------------------------------------

Traceback (most recent call last):

File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/mock.py", line 1201, in patched

return func(*args, **keywargs)

File "/home/travis/build/EFForg/OpenWireless/test/change_password_first_time_test.py", line 52, in test_change_password_first_time

uci.set.assert_called_once_with('openwireless.setup_state', 'setup-private-net')

File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/mock.py", line 845, in assert_called_once_with

raise AssertionError(msg)

AssertionError: Expected to be called once. Called 3 times.
```

**Comment by errolpais** [comment]
I was able to reproduce this issue with a clean checkout of master (d9dc7b3d0b291aa259a4d937031473bfae4beabb) on ubuntu 14.04 and running the ./install-dev-dependencies.sh script
